// Issue #108: temporary "What's New" banner shown after login when a new release
// (closed GitHub milestone) has shipped. Content comes from /whats-new.json,
// generated by .github/workflows/whats-new.yml from issues labeled `whats-new`.
// Dismissal is per device: localStorage stores the dismissed version, so the
// banner shows once per release per device. Renders nothing when there's no
// content or the current version was already dismissed.
import { useState, useEffect } from 'react';
import { X } from '../icons';

const DISMISS_KEY = 'whatsNewDismissedVersion';

export function WhatsNewBanner({ palette = {} }) {
  const p = {
    accent: '#2563eb',
    accentBg: '#eff6ff',
    border: '#bfdbfe',
    text: '#0f172a',
    textMuted: '#475569',
    ...palette,
  };
  const [data, setData] = useState(null);
  const [dismissed, setDismissed] = useState(false);

  useEffect(() => {
    let cancelled = false;
    fetch('/whats-new.json')
      .then((r) => (r.ok ? r.json() : null))
      .then((j) => {
        if (cancelled || !j?.version || !Array.isArray(j.items) || j.items.length === 0) return;
        if (localStorage.getItem(DISMISS_KEY) === j.version) return; // already seen this release
        setData(j);
      })
      .catch(() => {}); // banner is best-effort — never break the page
    return () => { cancelled = true; };
  }, []);

  if (!data || dismissed) return null;

  const dismiss = () => {
    try { localStorage.setItem(DISMISS_KEY, data.version); } catch { /* private mode */ }
    setDismissed(true);
  };

  return (
    <div style={{ background: p.accentBg, border: `1px solid ${p.border}`, borderRadius: '12px', padding: '14px 18px', marginBottom: '20px', position: 'relative' }}>
      <button
        onClick={dismiss}
        aria-label="Dismiss what's new"
        style={{ position: 'absolute', top: '10px', right: '10px', background: 'none', border: 'none', cursor: 'pointer', color: p.textMuted, padding: '4px' }}
      >
        <X size={15} />
      </button>
      <div style={{ fontSize: '14px', fontWeight: 800, color: p.accent, marginBottom: '8px' }}>
        🆕 What's New — {data.version}
      </div>
      <ul style={{ margin: 0, paddingLeft: '18px', display: 'flex', flexDirection: 'column', gap: '6px' }}>
        {data.items.map((item, i) => (
          <li key={i} style={{ fontSize: '13px', color: p.text, lineHeight: 1.45 }}>
            <span style={{ whiteSpace: 'pre-wrap' }}>{item.body}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}
